name: PR Issue Auto-Assignment

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: read

jobs:
  auto-assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.OPENWISP_BOT_APP_ID }}
          private-key: ${{ secrets.OPENWISP_BOT_PRIVATE_KEY }}

      - name: Checkout openwisp-utils bot branch
        uses: actions/checkout@v4
        with:
          repository: Eeshu-Yadav/openwisp-utils
          ref: issues/571-automate-assigning-unassigning-issues
          sparse-checkout: |
            openwisp_utils/bots
          sparse-checkout-cone-mode: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install "PyGithub>=2.0.0"

      - name: Run PR issue link bot
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          EVENT_DATA: ${{ toJson(github.event) }}
        run: |
          echo "$EVENT_DATA" > event.json
          python -m openwisp_utils.bots.auto_assign issue_assignment event.json
